# Generated by Django 4.2.4 on 2023-08-09 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0001_initial'),
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='arrival',
            new_name='checkin',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='depart',
            new_name='checkout',
        ),
        migrations.AddField(
            model_name='booking',
            name='room_number',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Rooms.room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('inside', 'inside'), ('checked', 'checked')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('other', 'other')], max_length=100),
        ),
    ]
