# Generated by Django 4.2.4 on 2023-08-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0002_rename_arrival_booking_checkin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
