# Generated by Django 4.2.4 on 2023-08-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0005_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout',
            field=models.DateField(),
        ),
    ]
