# Generated by Django 4.2.4 on 2023-08-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0006_alter_booking_checkin_alter_booking_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room_type',
            field=models.CharField(choices=[('delux', 'delux'), ('super delux', 'super delux'), ('Single', 'Single'), ('Double', 'Double')], max_length=100),
        ),
    ]
