# Generated by Django 4.2.4 on 2023-08-18 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0008_rename_decription_booking_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 8, 18, 14, 12, 33, 44985, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
