# Generated by Django 4.2.4 on 2023-08-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('room_type', models.CharField(max_length=100)),
                ('meal', models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('two', 'two'), ('all', 'all')], max_length=250)),
                ('bed_capacity', models.IntegerField()),
                ('air_condition', models.CharField(choices=[('AC', 'AC'), ('No AC', 'No AC')], max_length=100)),
                ('rent', models.IntegerField()),
                ('status', models.CharField(choices=[('booked', 'booked'), ('open', 'open'), ('inactive', 'inactive')], max_length=250)),
            ],
            options={
                'db_table': 'Room',
            },
        ),
    ]
