# Generated by Django 4.2.4 on 2023-08-20 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0005_room_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 8, 20, 5, 49, 9, 726483, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
