# Generated by Django 4.2.4 on 2023-08-10 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0001_initial'),
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='room_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Rooms.room'),
        ),
    ]
